# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - pyside6-project build
      - ln -sf $(pwd)/keylistener src/qml/keylistener
  run:
    deps: [build]
    cmds:
      - pyside6-project run
  clean:
    cmds:
      - pyside6-project clean
      - rm -rf src/qml/keylistener
